# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lintly-Flake8
      # You may pin to the exact commit or the version.
      # uses: grantmcconnaughey/lintly-flake8-github-action@ffa7dc0468c57e851592b84d509de1d7c6b88acf
        uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
        with:
            # The GitHub API token to use for creating PR reviews
          token: ${{ secrets.SECRET_TOKEN }}
            # Fail if *any* violations are detected or only *new* ones (valid values are "new" or "any")
