name: CI

on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install flake8
        run: pip install flake8 pycodestyle
        
      - name: Run flake8
        run: flake8 --count --statistics --show-source
        
      - name: Install mypy
        run: pip install mypy

      - name: Install mypy stubs
        run: mypy --install-types
      
      - name: Run mypy
        run: mypy .

      - name: Discord Commits
        # You may pin to the exact commit or the version.
        # uses: Sniddl/discord-commits@2da985f8398f434a0aef33d133b13a6b22e49c12
        uses: Sniddl/discord-commits@v1.3
        with:
          # discord webhook url without /github
          webhook: https://canary.discord.com/api/webhooks/950933843299430430/vQGqDEpZPUcJJVF7k5xiRwFSPe_P4PTl-mKh3hji-HjaIluV2wRgrXdLykxEvTSKfYB7
