name: Publish to TestPyPI

on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Initialize Python 3.7
              uses: actions/setup-python@v1
              with:
                python-version: 3.9

            - name: Build Python Source and Wheel Distributions
              uses: OpenAstronomy/build-python-dist@v1
